"""empty message

Revision ID: 6d8abebef80f
Revises: 1db3d979832b
Create Date: 2022-04-10 15:08:22.127881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8abebef80f'
down_revision = '1db3d979832b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cocktail', sa.Column('origin_id', sa.Integer(), nullable=False))
    op.add_column('cocktail', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('cocktail', sa.Column('region', sa.String(length=128), nullable=True))
    op.drop_index('ix_cocktail_origin', table_name='cocktail')
    op.create_index(op.f('ix_cocktail_country'), 'cocktail', ['country'], unique=False)
    op.create_index(op.f('ix_cocktail_origin_id'), 'cocktail', ['origin_id'], unique=False)
    op.create_index(op.f('ix_cocktail_region'), 'cocktail', ['region'], unique=False)
    op.create_foreign_key(None, 'cocktail', 'origin', ['origin_id'], ['id'])
    op.drop_column('cocktail', 'origin')
    op.add_column('ingredient', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.drop_index('ix_ingredient_origin', table_name='ingredient')
    op.drop_column('ingredient', 'origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('origin', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_ingredient_origin', 'ingredient', ['origin'], unique=False)
    op.drop_column('ingredient', 'ingredient_id')
    op.add_column('cocktail', sa.Column('origin', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'cocktail', type_='foreignkey')
    op.drop_index(op.f('ix_cocktail_region'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_origin_id'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_country'), table_name='cocktail')
    op.create_index('ix_cocktail_origin', 'cocktail', ['origin'], unique=False)
    op.drop_column('cocktail', 'region')
    op.drop_column('cocktail', 'country')
    op.drop_column('cocktail', 'origin_id')
    op.drop_table('origin')
    # ### end Alembic commands ###
